services:
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres} # Valor padrão caso a .env não exista
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-wallet_challenge_development}
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USERNAME:-postgres} -d ${DB_NAME:-wallet_challenge_development}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RAILS_ENV=development
      - DB_HOST=db
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-password}
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "rm -f tmp/pids/server.pid &&
               bundle install &&
               bin/rails db:prepare &&
               bin/rails s -b 0.0.0.0"
volumes:
  postgres_data:
